### ISSUE TITLE
Docs generation sometimes fails: "There is already an active transaction"

### ISSUE THREAD

**Issue by jp2masa** [knuckleswtf/scribe#255]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**

When I run `php artisan scribe:generate` sometimes it isn't able to connect to the database because apparently a transaction is already open. I actually modified the source a bit so the stack trace would show the `PDOException` message.

**Screenshots and stack traces:**

Stack trace:

```
🔊 info Processing route: [POST] item/{item}/comments/add
🚫 error Failed processing route: [POST] item/{item}/comments/add - Exception encountered.

   Exception

  Failed to connect to database connection 'pgsql'. Is the database running? If you aren't using this database, remove it from the `database_connections_to_transact` config array.PDOException: There is already an active transaction in /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:139
Stack trace:
#0 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(139): PDO->beginTransaction()
#1 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(115): Illuminate\Database\Connection->createTransaction()
#2 /var/www/app/vendor/knuckleswtf/scribe/src/Extracting/DatabaseTransactionHelpers.php(26): Illuminate\Database\Connection->beginTransaction()
#3 /var/www/app/vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/UseTransformerTags.php(36): Knuckles\Scribe\Extracting\Strategies\Responses\UseTransformerTags->startDbTransaction()
#4 /var/www/app/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(228): Knuckles\Scribe\Extracting\Strategies\Responses\UseTransformerTags->__invoke()
#5 /var/www/app/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(185): Knuckles\Scribe\Extracting\Extractor->iterateThroughStrategies()
#6 /var/www/app/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(119): Knuckles\Scribe\Extracting\Extractor->fetchResponses()
#7 /var/www/app/vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php(111): Knuckles\Scribe\Extracting\Extractor->processRoute()
#8 /var/www/app/vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php(322): Knuckles\Scribe\Commands\GenerateDocumentation->extractEndpointsInfoFromLaravelApp()
#9 /var/www/app/vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php(56): Knuckles\Scribe\Commands\GenerateDocumentation->extractEndpointsInfoAndWriteToDisk()
#10 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Knuckles\Scribe\Commands\GenerateDocumentation->handle()
#11 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#13 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#14 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#15 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#16 /var/www/app/vendor/symfony/console/Command/Command.php(299): Illuminate\Console\Command->execute()
#17 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#18 /var/www/app/vendor/symfony/console/Application.php(978): Illuminate\Console\Command->run()
#19 /var/www/app/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#20 /var/www/app/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#21 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\Component\Console\Application->run()
#22 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#23 /var/www/app/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#24 {main}

  at vendor/knuckleswtf/scribe/src/Extracting/DatabaseTransactionHelpers.php:28
     24▕             if (self::driverSupportsTransactions($driver)) {
     25▕                 try {
     26▕                     $driver->beginTransaction();
     27▕                 } catch (PDOException $e) {
  ➜  28▕                     throw new \Exception(
     29▕                         "Failed to connect to database connection '$connection'." .
     30▕                         " Is the database running?" .
     31▕                         " If you aren't using this database, remove it from the `database_connections_to_transact` config array." . $e
     32▕                     );

  1   vendor/knuckleswtf/scribe/src/Extracting/Strategies/Responses/UseTransformerTags.php:36
      Knuckles\Scribe\Extracting\Strategies\Responses\UseTransformerTags::startDbTransaction()

  2   vendor/knuckleswtf/scribe/src/Extracting/Extractor.php:228
      Knuckles\Scribe\Extracting\Strategies\Responses\UseTransformerTags::__invoke()

  3   vendor/knuckleswtf/scribe/src/Extracting/Extractor.php:185
      Knuckles\Scribe\Extracting\Extractor::iterateThroughStrategies()

  4   vendor/knuckleswtf/scribe/src/Extracting/Extractor.php:119
      Knuckles\Scribe\Extracting\Extractor::fetchResponses()

  5   vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php:111
      Knuckles\Scribe\Extracting\Extractor::processRoute()

  6   vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php:322
      Knuckles\Scribe\Commands\GenerateDocumentation::extractEndpointsInfoFromLaravelApp()

  7   vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php:56
      Knuckles\Scribe\Commands\GenerateDocumentation::extractEndpointsInfoAndWriteToDisk()

  8   vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
      Knuckles\Scribe\Commands\GenerateDocumentation::handle()

  9   vendor/laravel/framework/src/Illuminate/Container/Util.php:40
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  10  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
      Illuminate\Container\Util::unwrapIfClosure()

  11  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
      Illuminate\Container\BoundMethod::callBoundMethod()

  12  vendor/laravel/framework/src/Illuminate/Container/Container.php:651
      Illuminate\Container\BoundMethod::call()

  13  vendor/laravel/framework/src/Illuminate/Console/Command.php:136
      Illuminate\Container\Container::call()

  14  vendor/symfony/console/Command/Command.php:299
      Illuminate\Console\Command::execute()

  15  vendor/laravel/framework/src/Illuminate/Console/Command.php:121
      Symfony\Component\Console\Command\Command::run()

  16  vendor/symfony/console/Application.php:978
      Illuminate\Console\Command::run()

  17  vendor/symfony/console/Application.php:295
      Symfony\Component\Console\Application::doRunCommand()

  18  vendor/symfony/console/Application.php:167
      Symfony\Component\Console\Application::doRun()

  19  vendor/laravel/framework/src/Illuminate/Console/Application.php:92
      Symfony\Component\Console\Application::run()

  20  vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
      Illuminate\Console\Application::run()

  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**My environment:**
 - PHP version (from `php -v`): 7.4.3
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.48.2
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.3.0

**My Scribe config (minus the comments):**

```php

<?php

use Knuckles\Scribe\Extracting\Strategies;

return [

    'theme' => 'default',
    'title' => null,
    'description' => '',
    'base_url' => null,
    'routes' => [[
        'match' => [
            'domains' => ['*'],
            'prefixes' => ['*'],
            'versions' => ['v1'],
        ],
        'include' => [],
        'exclude' => [],
        'apply' => [
            'headers' => ['Content-Type' => 'application/json', 'Accept' => 'application/json'],
            'response_calls' => [
                'methods' => ['GET'],
                'config' => ['app.env' => 'documentation', 'app.debug' => false],
                'queryParams' => [],
                'bodyParams' => [],
                'fileParams' => [],
                'cookies' => [],
            ],
        ],
    ]],

    'type' => 'static',

    'static' => [
        'output_path' => 'public/docs',
    ],

    'laravel' => [
        'add_routes' => true,
        'docs_url' => '/docs',
        'middleware' => [],
    ],

    'try_it_out' => [
        'enabled' => true,
        'base_url' => null,
    ],

    'auth' => [
        'enabled' => false,
        'default' => false,
        'in' => 'bearer',
        'name' => 'key',
        'use_value' => env('SCRIBE_AUTH_KEY'),
        'placeholder' => '{YOUR_AUTH_KEY}',
        'extra_info' => 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.',
    ],
    'intro_text' => <<<INTRO
This documentation aims to provide all the information you need to work with our API.

<aside>As you scroll, you'll see code examples for working with the API in different programming languages in the dark area to the right (or as part of the content on mobile).
You can switch the language used with the tabs at the top right (or from the nav menu at the top left on mobile).</aside>
INTRO

    ,

    'example_languages' => [
        'bash',
        'javascript',
    ],

    'postman' => [
        'enabled' => true,
        'overrides' => [],
    ],

    'openapi' => [
        'enabled' => true,
        'overrides' => [],
    ],

    'default_group' => 'Endpoints',
    'logo' => false,
    'faker_seed' => null,

    'strategies' => [
        'metadata' => [
            Strategies\Metadata\GetFromDocBlocks::class,
        ],
        'urlParameters' => [
            Strategies\UrlParameters\GetFromLaravelAPI::class,
            Strategies\UrlParameters\GetFromLumenAPI::class,
            Strategies\UrlParameters\GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            Strategies\QueryParameters\GetFromFormRequest::class,
            Strategies\QueryParameters\GetFromInlineValidator::class,
            Strategies\QueryParameters\GetFromQueryParamTag::class,
        ],
        'headers' => [
            Strategies\Headers\GetFromRouteRules::class,
            Strategies\Headers\GetFromHeaderTag::class,
        ],
        'bodyParameters' => [
            Strategies\BodyParameters\GetFromFormRequest::class,
            Strategies\BodyParameters\GetFromInlineValidator::class,
            Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
        'responses' => [
            Strategies\Responses\UseTransformerTags::class,
            Strategies\Responses\UseResponseTag::class,
            Strategies\Responses\UseResponseFileTag::class,
            Strategies\Responses\UseApiResourceTags::class,
            Strategies\Responses\ResponseCalls::class,
        ],
        'responseFields' => [
            Strategies\ResponseFields\GetFromResponseFieldTag::class,
        ],
    ],

    'fractal' => [
        'serializer' => null,
    ],

    'routeMatcher' => \Knuckles\Scribe\Matching\RouteMatcher::class,
    'database_connections_to_transact' => [config('database.default'), config('database.default')]
];
```

**Comment by shalvah** [comment]
Hmmm, this shouldn't happen, since all transactions happen one after the other. Is your app running while this happens?

**Comment by jp2masa** [comment]
This is running in a Docker container, in the entrypoint script, which runs the following commands:

```
php artisan config:cache
php artisan route:cache
php artisan view:cache

php artisan migrate:fresh --seed --force

php artisan scribe:generate

php-fpm7.4 -D
nginx -g "daemon off;"
```

So apparently the app would only run on the last line (this script wasn't created by me, and I don't have much experience on this).

Additionally, if I open a bash shell in the container while the app is running, I get the same failure, intermittently. However, if I run `php artisan down` then `php artisan scribe:generate` always succeeds, so I'm using this as a workaround, and it didn't fail so far:

```
php artisan down
php artisan scribe:generate
php artisan up
```

**Comment by shalvah** [comment]
Hmm


Ah, I think this may be the issue. In your config, you have:

```php
 'database_connections_to_transact' => [config('database.default'), config('database.default')]
```

(I recognise that this isn't your fault; it's a bug from the upgrade command.^^^)

So maybe it's trying to start a transaction on the same connection twice. 


Setting it to one instance should fix it:

```php
 'database_connections_to_transact' => [config('database.default')]
```

If it still doesn't work, you can just empty the array and make sure you disable response calls or use a test database.

**Comment by jp2masa** [comment]
It works, thanks for the help!
