### ISSUE TITLE
Can't generate doc with isMethod() and route() function calls in FormRequests

### ISSUE THREAD

**Issue by tgalfa** [knuckleswtf/scribe#532]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
Hello

I use FormRequests for validation. The package generally works fine. But I encontered the following errors:

1. When I want to use `$this->isMethod('post')` or `$this->method()` function call in FormRequests
2. When I want to use `$this->route('item')` function call in FormRequests
The `php artisan scribe:generate` command fails to generate the doc for the related routes.

**Screenshots and stack traces:**
*isMethod('post')*
![Screenshot from 2022-10-11 16-01-43](https://user-images.githubusercontent.com/13517318/195117105-9663fbf3-5b3e-4753-bedd-454ae7e7b06a.png)
```php
 Call to a member function get() on null {"userId":3,"exception":"[object] (Error(code: 0): Call to a member function get() on null at /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/http-foundation/Request.php:1196)
[stacktrace]
#0 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/http-foundation/Request.php(1378): Symfony\\Component\\HttpFoundation\\Request->getMethod()
#1 /home/vagrant/code/adaptivemedia/amid-laravel/app/Http/Requests/UpdateSiteRequest.php(70): Symfony\\Component\\HttpFoundation\\Request->isMethod()
#2 [internal function]: App\\Http\\Requests\\UpdateSiteRequest->rules()
#3 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Strategies/GetFromFormRequestBase.php(71): call_user_func_array()
#4 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Strategies/GetFromFormRequestBase.php(51): Knuckles\\Scribe\\Extracting\\Strategies\\GetFromFormRequestBase->getRouteValidationRules()
#5 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Strategies/GetFromFormRequestBase.php(24): Knuckles\\Scribe\\Extracting\\Strategies\\GetFromFormRequestBase->getParametersFromFormRequest()
#6 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(209): Knuckles\\Scribe\\Extracting\\Strategies\\GetFromFormRequestBase->__invoke()
#7 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(158): Knuckles\\Scribe\\Extracting\\Extractor->iterateThroughStrategies()
#8 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(77): Knuckles\\Scribe\\Extracting\\Extractor->fetchBodyParameters()
#9 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php(122): Knuckles\\Scribe\\Extracting\\Extractor->processRoute()
#10 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php(69): Knuckles\\Scribe\\GroupedEndpoints\\GroupedEndpointsFromApp->extractEndpointsInfoFromLaravelApp()
#11 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php(47): Knuckles\\Scribe\\GroupedEndpoints\\GroupedEndpointsFromApp->extractEndpointsInfoAndWriteToDisk()
#12 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php(53): Knuckles\\Scribe\\GroupedEndpoints\\GroupedEndpointsFromApp->get()
#13 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Knuckles\\Scribe\\Commands\\GenerateDocumentation->handle()
#14 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#18 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\\Container\\Container->call()
#19 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#20 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\\Component\\Console\\Command\\Command->run()
#21 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/console/Application.php(1002): Illuminate\\Console\\Command->run()
#22 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#23 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#24 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#25 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(151): Illuminate\\Console\\Application->run()
#26 /home/vagrant/code/adaptivemedia/amid-laravel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}
"} 
```
*route*
![Screenshot from 2022-10-11 16-18-47](https://user-images.githubusercontent.com/13517318/195117227-3320a543-8cfe-43fe-b74d-188d4fc6021a.png)
```php
Call to a member function get() on null {"userId":3,"exception":"[object] (Error(code: 0): Call to a member function get() on null at /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/http-foundation/Request.php:1688)
[stacktrace]
#0 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/http-foundation/Request.php(982): Symfony\\Component\\HttpFoundation\\Request->prepareRequestUri()
#1 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/http-foundation/Request.php(1825): Symfony\\Component\\HttpFoundation\\Request->getRequestUri()
#2 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/http-foundation/Request.php(819): Symfony\\Component\\HttpFoundation\\Request->preparePathInfo()
#3 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Http/Request.php(164): Symfony\\Component\\HttpFoundation\\Request->getPathInfo()
#4 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Http/Request.php(176): Illuminate\\Http\\Request->path()
#5 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Routing/RouteParameterBinder.php(57): Illuminate\\Http\\Request->decodedPath()
#6 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Routing/RouteParameterBinder.php(35): Illuminate\\Routing\\RouteParameterBinder->bindPathParameters()
#7 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(368): Illuminate\\Routing\\RouteParameterBinder->parameters()
#8 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Strategies/GetFromFormRequestBase.php(48): Illuminate\\Routing\\Route->bind()
#9 [internal function]: Knuckles\\Scribe\\Extracting\\Strategies\\GetFromFormRequestBase->Knuckles\\Scribe\\Extracting\\Strategies\\{closure}()
#10 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Http/Request.php(618): call_user_func()
#11 /home/vagrant/code/adaptivemedia/amid-laravel/app/Http/Requests/UpdateSiteRequest.php(70): Illuminate\\Http\\Request->route()
#12 [internal function]: App\\Http\\Requests\\UpdateSiteRequest->rules()
#13 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Strategies/GetFromFormRequestBase.php(71): call_user_func_array()
#14 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Strategies/GetFromFormRequestBase.php(51): Knuckles\\Scribe\\Extracting\\Strategies\\GetFromFormRequestBase->getRouteValidationRules()
#15 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Strategies/GetFromFormRequestBase.php(24): Knuckles\\Scribe\\Extracting\\Strategies\\GetFromFormRequestBase->getParametersFromFormRequest()
#16 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(209): Knuckles\\Scribe\\Extracting\\Strategies\\GetFromFormRequestBase->__invoke()
#17 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(158): Knuckles\\Scribe\\Extracting\\Extractor->iterateThroughStrategies()
#18 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Extracting/Extractor.php(77): Knuckles\\Scribe\\Extracting\\Extractor->fetchBodyParameters()
#19 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php(122): Knuckles\\Scribe\\Extracting\\Extractor->processRoute()
#20 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php(69): Knuckles\\Scribe\\GroupedEndpoints\\GroupedEndpointsFromApp->extractEndpointsInfoFromLaravelApp()
#21 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/GroupedEndpoints/GroupedEndpointsFromApp.php(47): Knuckles\\Scribe\\GroupedEndpoints\\GroupedEndpointsFromApp->extractEndpointsInfoAndWriteToDisk()
#22 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php(53): Knuckles\\Scribe\\GroupedEndpoints\\GroupedEndpointsFromApp->get()
#23 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Knuckles\\Scribe\\Commands\\GenerateDocumentation->handle()
#24 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#26 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#27 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#28 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\\Container\\Container->call()
#29 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#30 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\\Component\\Console\\Command\\Command->run()
#31 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/console/Application.php(1002): Illuminate\\Console\\Command->run()
#32 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#33 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#34 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#35 /home/vagrant/code/adaptivemedia/amid-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(151): Illuminate\\Console\\Application->run()
#36 /home/vagrant/code/adaptivemedia/amid-laravel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#37 {main}
"} 
```

**My environment:**
 - PHP version (from `php -v`): 8.1.6
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 9.34.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 4.0.0

**My Scribe config (minus the comments):**
```php
use Knuckles\Scribe\Extracting\Strategies;

return [

    'theme' => 'default',
    'title' => null,
    'description' => '',
    'base_url' => null,
    'routes' => [
        [
            'match' => [
                'prefixes' => ['api/*'],
                'domains' => ['*'],
                'versions' => ['v1'],
            ],
            'include' => [
            ],
            'exclude' => [
            ],
            'apply' => [
                'headers' => [
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json',
                ],
                'response_calls' => [
                    'methods' => ['GET'],
                    'config' => [
                        'app.env' => 'documentation',
                        'app.debug' => false,
                    ],
                    'queryParams' => [
                    ],
                    'bodyParams' => [
                    ],
                    'fileParams' => [
                    ],
                    'cookies' => [
                    ],
                ],
            ],
        ],
    ],
    'type' => 'laravel',
    'static' => [
        'output_path' => 'public/docs',
    ],
    'laravel' => [
        'add_routes' => true,
        'docs_url' => '/docs',
        'middleware' => [],
        'assets_directory' => null,
    ],

    'try_it_out' => [
        'enabled' => false,
        'base_url' => null,
        'use_csrf' => true,
        'csrf_url' => '/api/sanctum/csrf-cookie',
    ],
    'auth' => [
        'enabled' => true,
        'default' => false,
        'in' => 'bearer',
        'name' => 'Authorization',
        'use_value' => env('SCRIBE_AUTH_KEY'),
        'placeholder' => '{YOUR_AUTH_KEY}',
        'extra_info' => 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.',
    ],
    'intro_text' => <<<'INTRO'
This documentation aims to provide all the information you need to work with our API.

<aside>As you scroll, you'll see code examples for working with the API in different programming languages in the dark area to the right (or as part of the content on mobile).
You can switch the language used with the tabs at the top right (or from the nav menu at the top left on mobile).</aside>
INTRO
    ,
    'example_languages' => [
        'bash',
        'javascript',
    ],
    'postman' => [
        'enabled' => true,
        'overrides' => [
            'variable.1' => [
                'id' => 'token',
                'key' => 'token',
                'type' => 'string',
                'name' => 'string',
                'value' => 'Bearer',
            ],
        ],
    ],
    'openapi' => [
        'enabled' => true,
        'overrides' => [
        ],
    ],
    'logo' => false,
    'strategies' => [
        'metadata' => [
            Strategies\Metadata\GetFromDocBlocks::class,
        ],
        'urlParameters' => [
            Strategies\UrlParameters\GetFromLaravelAPI::class,
            Strategies\UrlParameters\GetFromLumenAPI::class,
            Strategies\UrlParameters\GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            Strategies\QueryParameters\GetFromFormRequest::class,
            Strategies\QueryParameters\GetFromInlineValidator::class,
            Strategies\QueryParameters\GetFromQueryParamTag::class,
        ],
        'headers' => [
            Strategies\Headers\GetFromRouteRules::class,
            Strategies\Headers\GetFromHeaderTag::class,
        ],
        'bodyParameters' => [
            Strategies\BodyParameters\GetFromFormRequest::class,
            Strategies\BodyParameters\GetFromInlineValidator::class,
            Strategies\BodyParameters\GetFromBodyParamTag::class,
        ],
        'responses' => [
            Strategies\Responses\UseTransformerTags::class,
            Strategies\Responses\UseApiResourceTags::class,
            Strategies\Responses\UseResponseTag::class,
            Strategies\Responses\UseResponseFileTag::class,
            Strategies\Responses\ResponseCalls::class,
        ],
        'responseFields' => [
            Strategies\ResponseFields\GetFromResponseFieldTag::class,
        ],
    ],
    'fractal' => [
        'serializer' => null,
    ],
    'routeMatcher' => \Knuckles\Scribe\Matching\RouteMatcher::class,
    'database_connections_to_transact' => [config('database.default')],
    'groups' => [
        'default' => 'Endpoints',
        'order' => [
            'Site' => [
                'Site Store.',
                'Site List.',
                'Site Show.',
            ],
        ],
    ],
    'examples' => [
        'faker_seed' => null,
        'models_source' => ['factoryCreate', 'factoryMake', 'databaseFirst'],
    ],
];
```

**Comment by shalvah** [comment]
The problem here is that when Scribe instantiates FormRequests, it does just that. It doesn't do it in the context of a full request, just calls `new YourFormRequest`, so most things that depend on the request state are broken. Maybe I might take a look at how we can patch that better. Maybe `app(YourFormRequest::class)` might just work, or we might need to create a fake request object and bind it. 🤔 

In the meantime, you can use the [`instantiateFormRequestUsing()` hook](https://scribe.knuckles.wtf/laravel/hooks#instantiateformrequestusing).to customise how FormRequests are created. You could try using the `app` helper in there, for instance.

**Comment by shalvah** [comment]
Have you tried the `beforeResponseCall()` hook?

**Comment by shalvah** [comment]
Just  realised this is the same issue as #585 , which I've fixed now. However, I think your issue @ClintWinter is a different issue relating to response calls, not form requests. I think `beforeResponseCall` would be applicable to your case.

**Comment by ClintWinter** [comment]
The code sample I used would be inside a request class. It would be attempting to access the comment via route-model binding. For example a route like `Route::patch('/comments/{comment}', ...)`. The Request class tries to access the comment as a model. That would need to be handled with `beforeResponseCall`?

**Comment by shalvah** [comment]
Can't say more unless I know the specific error you're getting (open a new issue with details). But the basic form request strategy (which generates _request parameters_) just instantiates your form request and calls `rules()`. It does not invoke any authorisation or route model binding. Those are things that might happen during response calls (for generating _responses_).
