### ISSUE TITLE
Try it out unable to get base Url

### ISSUE THREAD

**Issue by markheramis** [knuckleswtf/scribe#798]
### Scribe version

4.9

### PHP version

8.1

### Framework

Laravel

### Framework version

v9.52.16

### Scribe config

```ruby
title => "Laravel-Restful-API"
base_url => "http://localhost:8000"
type => "laravel"
static.output_path => "storage/app/public/docs"
try_it_out.base_url => "http://localhost:8000"
auth.enabled => true
auth.name => "Authorization"
logo => "/logo.png"
strategies.metadata => removed Knuckles\Scribe\Extracting\Strategies\Metadata\GetFromMetadataAttributes
strategies.urlParameters => added Knuckles\Scribe\Extracting\Strategies\UrlParameters\GetFromLumenAPI: removed Knuckles\Scribe\Extracting\Strategies\UrlParameters\GetFromUrlParamAttribute
strategies.queryParameters => removed Knuckles\Scribe\Extracting\Strategies\QueryParameters\GetFromFormRequest, Knuckles\Scribe\Extracting\Strategies\QueryParameters\GetFromInlineValidator, Knuckles\Scribe\Extracting\Strategies\QueryParameters\GetFromQueryParamAttribute
strategies.headers => added Knuckles\Scribe\Extracting\Strategies\Headers\GetFromRouteRules: removed Knuckles\Scribe\Extracting\Strategies\Headers\GetFromHeaderAttribute, [
    'override',
    [
        'Content-Type' => 'application/json',
        'Accept' => 'application/json',
    ],
]
strategies.bodyParameters => removed Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromInlineValidator, Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromBodyParamAttribute
strategies.responses => added Knuckles\Scribe\Extracting\Strategies\Responses\ResponseCalls: removed Knuckles\Scribe\Extracting\Strategies\Responses\UseResponseAttributes, [
    'Knuckles\\Scribe\\Extracting\\Strategies\\Responses\\ResponseCalls',
    [
        'only' => [
            'GET *',
        ],
    ],
]
strategies.responseFields => removed Knuckles\Scribe\Extracting\Strategies\ResponseFields\GetFromResponseFieldAttribute
fractal.serializer => "League\\Fractal\\Serializer\\JsonApiSerializer"
```

### What happened?

I try to submit any of the requests from try it out feature and will not be able to submit it throwing t he following error on the javascript console:

```
Error while making request:  TypeError: Failed to construct 'URL': Invalid URL
    at makeAPICall (tryitout-4.29.0.js:92:17)
    at tryitout-4.29.0.js:256:40
```
and on the execution-error element I get this

```html
<span id="execution-error-POSTapi-auth-login">
    <blockquote>Request failed with error:</blockquote>
    <pre><code id="execution-error-message-POSTapi-auth-login" class="hljs language-undefined">Failed to construct 'URL': Invalid URL</code></pre>
</span>
```
![image](https://github.com/knuckleswtf/scribe/assets/6801816/b5d51e41-c323-40a7-b6bd-9cf12d7ac705)

The reason is that the try it out feature is unable to get the try it out base url since it is defined as

```php
var tryItOutBaseUrl = "{{ $tryItOut['base_url'] ?? config('app.url') }}";
```
From [here ](https://github.com/knuckleswtf/scribe/blob/4.29.0/resources/views/themes/default/index.blade.php#L36) but when the button is clicked it will assembly the URL for the request based on the window.tryItOutBaseUrl

```javascript
const url = new URL(window.tryItOutBaseUrl + '/' + path.replace(/^\//, ''));
```
found [here](https://github.com/knuckleswtf/scribe/blob/4.29.0/resources/js/tryitout.js#L92C5-L92C81) and also [here](https://github.com/knuckleswtf/scribe/blob/4.29.0/resources/js/tryitout.js#L122) instead of doing

```javascript
const url = new URL(tryItOutBaseUrl + '/' + path.replace(/^\//, ''));
```

and

```javascript
return fetch(url, {
        method,
        headers,
        body: method === 'GET' ? undefined : body,
        signal: window.abortControllers[endpointId].signal,
        referrer: window.tryItOutBaseUrl,
        mode: 'cors',
        credentials: 'same-origin',
    })
```

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by markheramis** [comment]
Sorry for the confusion, it looks like it is resolved now.

I tried
```html
<script>
   console.log(tryItOutBaseUrl);
   console.log(window.tryItOutBaseUrl);
</script>
```
And they displayed the same value now.
Odd that I had the same code below my page and didn't output same few days ago.

Can't reproduce the problem anymore.

Thank you @shalvah
